### ISSUE TITLE
Safari Browser: Does not support WebGL and hence space tour is not displayed

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/ncbs-modular#209]

**Comment by salus-sage** [comment]
You may have to enable webgl in settings, refer to this link
http://onvert.com/guides/enable-webgl-safari/

**Comment by vaishnavisv** [comment]
After enabling the web gl its working fine

**Comment by salus-sage** [comment]
You can close the issue as resolved. However, put this comment of enabling
webgl settings, in the cross browser testing issue as documentation.


On 3 Oct 2017 5:02 p.m., "vaishnavisv" <notifications@github.com> wrote:

After enabling the web gl its working fine

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/janastu/ncbs-modular/issues/209#issuecomment-333814982>,
or mute the thread
