### ISSUE TITLE
Sitemap.xml needs to be created at the root of the application for SEO friendly

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-modular#91]

**Comment by pradeepc** [comment]
Created sitemap.xml file for the site url's.
Need to check for image and video url's with Bhanu.

http://localhost/ncbs-modular/sitemap.xml

**Comment by salus-sage** [comment]
No need to link any images or multimedia, only text and links are enough.

**Comment by pradeepc** [comment]
https://janastu.github.io/ncbs-modular/sitemap.xml  Check.

**Comment by salus-sage** [comment]
Please validate the xml and update the report

**Comment by salus-sage** [comment]
is the validated xml pushed?

**Comment by pradeepc** [comment]
I didnt push yet, i will push tomorrow morning.

On Aug 4, 2017 23:17, "Bhanu" <notifications@github.com> wrote:

is the validated xml pushed?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/janastu/ncbs-modular/issues/91#issuecomment-320311525>,
or mute the thread
